/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geocatch.view;
import geocatch.model.Functions;

/**
 *
 * @author yan
 */
public class MyMain extends javax.swing.JFrame {
    
    private static final Functions Funcs = new Functions ();  
   
    public static int n = 0;
    
    

       
    public MyMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        CloseButton = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        MapButton = new javax.swing.JButton();
        QuizButton1 = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        CapitalButton = new javax.swing.JButton();
        QuizButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(46, 127, 254));
        jPanel3.setBorder(null);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setForeground(new java.awt.Color(254, 254, 254));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 12));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/switch (1).png"))); // NOI18N
        CloseButton.setBorderPainted(false);
        CloseButton.setContentAreaFilled(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel3.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 50, 50));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 30, 12));

        MapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil-map.png"))); // NOI18N
        MapButton.setBorderPainted(false);
        MapButton.setContentAreaFilled(false);
        MapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 40));

        QuizButton1.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        QuizButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/test-quiz.png"))); // NOI18N
        QuizButton1.setBorderPainted(false);
        QuizButton1.setContentAreaFilled(false);
        QuizButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(QuizButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 140, 60, 56));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 30, 12));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 720));

        jPanel1.setBackground(new java.awt.Color(51, 106, 205));

        CapitalButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        CapitalButton.setForeground(new java.awt.Color(1, 1, 1));
        CapitalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil (2).png"))); // NOI18N
        CapitalButton.setText("Quero estudar pelo mapa");
        CapitalButton.setBorderPainted(false);
        CapitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitalButtonActionPerformed(evt);
            }
        });

        QuizButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        QuizButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/round.png"))); // NOI18N
        QuizButton.setText("Quero testar o que aprendi!");
        QuizButton.setBorderPainted(false);
        QuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(CapitalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QuizButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CapitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 1170, 510));

        jPanel2.setBackground(new java.awt.Color(78, 121, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("GeoCatch");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Geo Aprendizado");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/tasdasflkm.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1170, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitalButtonActionPerformed
        // TODO add your handling code here:
        
        new MapView().setVisible(true);//que quer abrir
     dispose();
     
    }//GEN-LAST:event_CapitalButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:

        new MyMain().setVisible(true);//que quer abrir
        dispose();

    }//GEN-LAST:event_HomeButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);
        
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void MapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButtonActionPerformed
        // TODO add your handling code here:
         new MapView().setVisible(true);//que quer abrir
     dispose();
    }//GEN-LAST:event_MapButtonActionPerformed

    private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButtonActionPerformed
        // TODO add your handling code here:
        
        new QuizExplain().setVisible(true);//que quer abrir
        
        dispose();
        
    }//GEN-LAST:event_QuizButtonActionPerformed

    private void QuizButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButton1ActionPerformed
        // TODO add your handling code here:
        new QuizExplain().setVisible(true);//que quer abrir
        
        dispose();
    }//GEN-LAST:event_QuizButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*
          Funcs.CreateDB(Funcs.getFunctionsName(0), Funcs.getDBCapital());
          Funcs.CreateDB(Funcs.getFunctionsName(1), Funcs.getDBFu());
          Funcs.CreateDB(Funcs.getFunctionsName(2), Funcs.getDBPopulation());
          Funcs.CreateDB(Funcs.getFunctionsName(3), Funcs.getDBCountryBorder());
          Funcs.CreateDB(Funcs.getFunctionsName(4), Funcs.getDBFrontier());
          Funcs.CreateDB(Funcs.getFunctionsName(5), Funcs.getDBRegion());
          Funcs.CreateDB(Funcs.getFunctionsName(6), Funcs.getDBArea());
          Funcs.CreateDB(Funcs.getFunctionsName(7), Funcs.getDBCoastalState());

          */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMain().setVisible(true);
                new MyMain().setDefaultCloseOperation(0);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapitalButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton MapButton;
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton QuizButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    // End of variables declaration//GEN-END:variables
}
