/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geocatch.view;
import geocatch.model.*;
/**
 *
 * @author yan
 */
public class QuickQuiz extends javax.swing.JFrame {
    
    Questions NewQuiz = new Questions();
    public QuickQuiz() {
        initComponents();
        AAlternative.setEnabled(false);
        BAlternative.setEnabled(false);
        CAlternative.setEnabled(false);
        DAlternative.setEnabled(false);
        
    };
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        startbutton = new javax.swing.JButton();
        nquestion = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        nota = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        questionlabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        BAlternative = new javax.swing.JButton();
        AAlternative = new javax.swing.JButton();
        CAlternative = new javax.swing.JButton();
        DAlternative = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        CloseButton = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        MapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 106, 205));
        jPanel7.setBorder(null);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(78, 121, 196));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Quiz rápido");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel9.setBackground(new java.awt.Color(70, 122, 214));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 12, -1, -1));

        startbutton.setFont(new java.awt.Font("URW Gothic L", 0, 60)); // NOI18N
        startbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/start (1).png"))); // NOI18N
        startbutton.setText("Clique para iniciar");
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });
        jPanel9.add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 120));

        nquestion.setFont(new java.awt.Font("URW Gothic L", 0, 70)); // NOI18N
        nquestion.setText("0");
        jPanel9.add(nquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel17.setText("Questão");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 110));

        jLabel18.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel18.setText("Sua nota");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        nota.setFont(new java.awt.Font("URW Gothic L", 0, 70)); // NOI18N
        nota.setText("0");
        jPanel9.add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1040, 120));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel1.setBackground(new java.awt.Color(64, 85, 121));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionlabel.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        questionlabel.setForeground(new java.awt.Color(254, 254, 254));
        questionlabel.setText("                                                                        Boa Sorte! :)");
        questionlabel.setToolTipText("");
        jPanel1.add(questionlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1140, 150));

        jPanel11.setBackground(new java.awt.Color(123, 153, 205));

        BAlternative.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        BAlternative.setText("B");
        BAlternative.setBorder(null);
        BAlternative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlternativeActionPerformed(evt);
            }
        });

        AAlternative.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        AAlternative.setText("A");
        AAlternative.setBorder(null);
        AAlternative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAlternativeActionPerformed(evt);
            }
        });

        CAlternative.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        CAlternative.setText("C");
        CAlternative.setBorder(null);
        CAlternative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAlternativeActionPerformed(evt);
            }
        });

        DAlternative.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        DAlternative.setText("D");
        DAlternative.setBorder(null);
        DAlternative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAlternativeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DAlternative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAlternative, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
                    .addComponent(BAlternative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AAlternative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(AAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1150, 390));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 1190, 560));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 0, 1370, 720));

        jPanel3.setBackground(new java.awt.Color(46, 127, 254));
        jPanel3.setBorder(null);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setForeground(new java.awt.Color(254, 254, 254));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 12));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/switch (1).png"))); // NOI18N
        CloseButton.setBorderPainted(false);
        CloseButton.setContentAreaFilled(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel3.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 50, 70));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 30, 12));

        MapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil-map.png"))); // NOI18N
        MapButton.setBorderPainted(false);
        MapButton.setContentAreaFilled(false);
        MapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:

        new MyMain().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void MapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButtonActionPerformed
        // TODO add your handling code here:
        new MapView().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_MapButtonActionPerformed

    private void BAlternativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlternativeActionPerformed
        // TODO add your handling code here:
        NewQuiz.ClickParser("B");
        nota.setText(NewQuiz.getNota().toString());
        
        
    if(nquestion.getText() != "10"){
          
            nquestion.setText((NewQuiz.getNQuestion().toString()));
            startQuiz();
        }
    }//GEN-LAST:event_BAlternativeActionPerformed

    private void CAlternativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAlternativeActionPerformed
        // TODO add your handling code here:
        NewQuiz.ClickParser("C");
       nota.setText(NewQuiz.getNota().toString());
      if(nquestion.getText() != "10"){
          
            nquestion.setText((NewQuiz.getNQuestion().toString()));
            startQuiz();
        }
    }//GEN-LAST:event_CAlternativeActionPerformed

    private void DAlternativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAlternativeActionPerformed
        // TODO add your handling code here:
        NewQuiz.ClickParser("D");
        nota.setText(NewQuiz.getNota().toString());
       if(nquestion.getText() != "10"){
          
            nquestion.setText((NewQuiz.getNQuestion().toString()));
            startQuiz();
        }
    }//GEN-LAST:event_DAlternativeActionPerformed

    private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
        // TODO add your handling code here:
        AAlternative.setEnabled(true);
        BAlternative.setEnabled(true);
        CAlternative.setEnabled(true);
        DAlternative.setEnabled(true);
        
        startbutton.setVisible(false);
        
        if(NewQuiz.getNQuestion() < 10){
           //startQuiz();
           NewQuiz.GenerateFuncName(questionlabel, AAlternative,BAlternative, CAlternative, DAlternative);
        Integer as = NewQuiz.getNQuestion() -1;
         nquestion.setText((as.toString()));
        }
        
    }//GEN-LAST:event_startbuttonActionPerformed

    private void AAlternativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAlternativeActionPerformed
        // TODO add your handling code here:
        
        NewQuiz.ClickParser("A");
       nota.setText(NewQuiz.getNota().toString());
       if(NewQuiz.getNQuestion() < 10){
          
            nquestion.setText((NewQuiz.getNQuestion().toString()));
            startQuiz();
        }else{
            new QuizEnd(NewQuiz).setVisible(true);
            dispose();
       }
    }//GEN-LAST:event_AAlternativeActionPerformed

    public void startQuiz(){
        if(NewQuiz.getNQuestion() < 10){
            System.out.println("nnn "+nquestion.getText());
          System.out.println("mmm "+NewQuiz.getNQuestion().toString());
        NewQuiz.GenerateFuncName(questionlabel, AAlternative,BAlternative, CAlternative, DAlternative);
            nquestion.setText((NewQuiz.getNQuestion().toString()));
            
        }else if(NewQuiz.getNQuestion() == 10){
            new QuizEnd(NewQuiz).setVisible(true);
            dispose();
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        /* Create and display the form */
     java.awt.EventQueue.invokeLater(new Runnable() {
              
            public void run() {
                
                new QuickQuiz().setVisible(true);
                 
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AAlternative;
    private javax.swing.JButton BAlternative;
    private javax.swing.JButton CAlternative;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DAlternative;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton MapButton;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JLabel nota;
    private javax.swing.JLabel nquestion;
    private javax.swing.JLabel questionlabel;
    private javax.swing.JButton startbutton;
    // End of variables declaration//GEN-END:variables
}
