/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geocatch.view;

import geocatch.model.Questions;
import javax.swing.ImageIcon;

/**
 *
 * @author yan
 */
public class QuizEnd extends javax.swing.JFrame {

    /**
     * Creates new form QuizEnd
     */
    public QuizEnd(Questions NewQuestion) {
        
        initComponents();
        if(NewQuestion.getNota() <= 10 && NewQuestion.getNota() >=8){
            
            notafinal.setText(NewQuestion.getNota().toString());
            endmessage.setText("Vejo que andou estudando, continue assim! o/");
            medallabel.setText("Ganhou medalha de prata");
            ImageIcon reward = new ImageIcon(this.getClass().getResource("/geocatch/draw/badge (2).png"));
            rewardlabel.setIcon(reward);
        }else if(NewQuestion.getNota() <8 && NewQuestion.getNota() >=5){
            
            notafinal.setText(NewQuestion.getNota().toString());
            endmessage.setText("Quaaaase lá, mas você está precisando estudar mais :)");
            medallabel.setText("Ganhou medalha de bronze");
           // ImageIcon reward = new ImageIcon("/home/yan/Documentos/GeoCatch/src/geocatch/draw/badge (3).png");
            ImageIcon reward = new ImageIcon(this.getClass().getResource("/geocatch/draw/badge (3).png"));
            rewardlabel.setIcon(reward);
        }else if(NewQuestion.getNota() <5){
            
            notafinal.setText(NewQuestion.getNota().toString());
            endmessage.setText("Vejo que você não tem estudado, precisa se esforçar mais");
            medallabel.setText("Ganhou fita de boa tentativa");
           // ImageIcon reward = new ImageIcon("/home/yan/Documentos/GeoCatch/src/geocatch/draw/ribbon.png");
           ImageIcon reward = new ImageIcon(this.getClass().getResource("/geocatch/draw/ribbon.png"));
            rewardlabel.setIcon(reward);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        MapButton = new javax.swing.JButton();
        QuizButton1 = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JSeparator();
        CloseButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HomeButton1 = new javax.swing.JButton();
        MapButton1 = new javax.swing.JButton();
        MapButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        notafinal = new javax.swing.JLabel();
        endmessage = new javax.swing.JLabel();
        desempenholabel = new javax.swing.JLabel();
        rewardlabel = new javax.swing.JLabel();
        medallabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(46, 127, 254));
        jPanel3.setBorder(null);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setForeground(new java.awt.Color(254, 254, 254));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 12));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 30, 12));

        MapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil-map.png"))); // NOI18N
        MapButton.setBorderPainted(false);
        MapButton.setContentAreaFilled(false);
        MapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 40));

        QuizButton1.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        QuizButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/test-quiz.png"))); // NOI18N
        QuizButton1.setBorderPainted(false);
        QuizButton1.setContentAreaFilled(false);
        QuizButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(QuizButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 50, 56));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 30, 12));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/switch (1).png"))); // NOI18N
        CloseButton.setBorderPainted(false);
        CloseButton.setContentAreaFilled(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel3.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 50, 50));

        jPanel7.setBackground(new java.awt.Color(51, 106, 205));
        jPanel7.setBorder(null);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(78, 121, 196));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Acabou \\o/");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/flag.png"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        HomeButton1.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        HomeButton1.setForeground(new java.awt.Color(1, 1, 1));
        HomeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline.png"))); // NOI18N
        HomeButton1.setText("Voltar");
        HomeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(HomeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 210, 40));

        MapButton1.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MapButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/replay-arrow.png"))); // NOI18N
        MapButton1.setText("Recomeçar");
        MapButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(MapButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 210, 40));

        MapButton2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MapButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil-map.png"))); // NOI18N
        MapButton2.setText("Estudar mais");
        MapButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(MapButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 210, 40));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 160));

        jPanel1.setBackground(new java.awt.Color(123, 153, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notafinal.setFont(new java.awt.Font("URW Gothic L", 0, 60)); // NOI18N
        notafinal.setForeground(new java.awt.Color(254, 254, 254));
        notafinal.setText("0");
        jPanel1.add(notafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        endmessage.setFont(new java.awt.Font("URW Gothic L", 0, 36)); // NOI18N
        endmessage.setForeground(new java.awt.Color(254, 254, 254));
        endmessage.setText("Parabéns, você é incrível, continue assim!");
        jPanel1.add(endmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));
        jPanel1.add(desempenholabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        rewardlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/badge (1).png"))); // NOI18N
        jPanel1.add(rewardlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -10, -1, -1));

        medallabel.setFont(new java.awt.Font("URW Gothic L", 0, 36)); // NOI18N
        medallabel.setForeground(new java.awt.Color(254, 254, 254));
        medallabel.setText("Ganhou medalha de ouro");
        jPanel1.add(medallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("Sua nota foi");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 1080, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:

        new MyMain().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void MapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButtonActionPerformed
        // TODO add your handling code here:
        new MapView().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_MapButtonActionPerformed

    private void HomeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton1ActionPerformed
        // TODO add your handling code here:
         new MyMain().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_HomeButton1ActionPerformed

    private void MapButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButton1ActionPerformed
        // TODO add your handling code here:
          new QuickQuiz().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_MapButton1ActionPerformed

    private void MapButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MapButton2ActionPerformed

    private void QuizButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButton1ActionPerformed
        // TODO add your handling code here:
        new QuizExplain().setVisible(true);//que quer abrir
        
        dispose();
    }//GEN-LAST:event_QuizButton1ActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);

    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private Questions NewQuestion;
            public void run() {
                new QuizEnd(NewQuestion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton HomeButton1;
    private javax.swing.JButton MapButton;
    private javax.swing.JButton MapButton1;
    private javax.swing.JButton MapButton2;
    private javax.swing.JButton QuizButton1;
    private javax.swing.JLabel desempenholabel;
    private javax.swing.JLabel endmessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JLabel medallabel;
    private javax.swing.JLabel notafinal;
    private javax.swing.JLabel rewardlabel;
    // End of variables declaration//GEN-END:variables
}
