/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geocatch.view;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author yan
 */
public class QuizExplain extends javax.swing.JFrame {

    /**
     * Creates new form QuizExplain
     */
    public QuizExplain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        MapButton4 = new javax.swing.JButton();
        HomeButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        HomeButton3 = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        MapButton3 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        ParaButton3 = new javax.swing.JButton();
        RondoniaButton3 = new javax.swing.JButton();
        RoraimaButton3 = new javax.swing.JButton();
        TocantinsButton3 = new javax.swing.JButton();
        MatoGrossoDoSulBUtton3 = new javax.swing.JButton();
        RioGrandeDoSulBUtton3 = new javax.swing.JButton();
        AcreButton8 = new javax.swing.JButton();
        AmazonasButton4 = new javax.swing.JButton();
        AmapaButton3 = new javax.swing.JButton();
        MaranhaoButton3 = new javax.swing.JButton();
        PiauiButton3 = new javax.swing.JButton();
        BahiaButton3 = new javax.swing.JButton();
        SantacatButton3 = new javax.swing.JButton();
        ParanaButton3 = new javax.swing.JButton();
        SaoPauloButton3 = new javax.swing.JButton();
        GoiasButton3 = new javax.swing.JButton();
        MinasGeraisButton3 = new javax.swing.JButton();
        RioDEJaneiroButton3 = new javax.swing.JButton();
        ESButton3 = new javax.swing.JButton();
        SergipeButton3 = new javax.swing.JButton();
        ParaibaButton3 = new javax.swing.JButton();
        PernambucoButton3 = new javax.swing.JButton();
        RGDNButton3 = new javax.swing.JButton();
        MatoGrossoButton19 = new javax.swing.JButton();
        CearaButton3 = new javax.swing.JButton();
        AlagoasButton3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        Regiões3 = new javax.swing.JButton();
        Geral3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        FUlabel3 = new javax.swing.JLabel();
        CapitalLabel3 = new javax.swing.JLabel();
        RegionLabel3 = new javax.swing.JLabel();
        PopulationLabel3 = new javax.swing.JLabel();
        AreaLabel3 = new javax.swing.JLabel();
        CoastalLabel3 = new javax.swing.JLabel();
        FrontierLabel3 = new javax.swing.JLabel();
        CuriosityLabel3 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel24 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        NomeEstado = new javax.swing.JLabel();
        QuizButton1 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(51, 106, 205));
        jPanel16.setBorder(null);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(78, 121, 196));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(254, 254, 254));
        jLabel31.setText("Quiz rápido");
        jPanel17.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel47.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(254, 254, 254));
        jLabel47.setText("É hora de mostrar que está preparado!");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 120));

        jLabel48.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(254, 254, 254));
        jLabel48.setText("Você precisará responder 10 questões aleatórias ");
        jPanel16.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 590, -1));

        MapButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazilzao.png"))); // NOI18N
        MapButton4.setBorderPainted(false);
        MapButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButton4ActionPerformed(evt);
            }
        });
        jPanel16.add(MapButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 290, 260));

        HomeButton4.setForeground(new java.awt.Color(254, 254, 254));
        HomeButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline (1).png"))); // NOI18N
        HomeButton4.setBorderPainted(false);
        HomeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton4ActionPerformed(evt);
            }
        });
        jPanel16.add(HomeButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 290, 260));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/student (1).png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, -1, 260));

        jLabel33.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(254, 254, 254));
        jLabel33.setText("Estou pronto!");
        jPanel16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, -1, -1));

        jLabel49.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(254, 254, 254));
        jLabel49.setText("Preciso estudar mais");
        jPanel16.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        jLabel51.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(254, 254, 254));
        jLabel51.setText("Voltar");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, -1));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1170, 720));

        jPanel19.setBackground(new java.awt.Color(46, 127, 254));
        jPanel19.setBorder(null);
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton3.setForeground(new java.awt.Color(254, 254, 254));
        HomeButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/house-outline.png"))); // NOI18N
        HomeButton3.setBorderPainted(false);
        HomeButton3.setContentAreaFilled(false);
        HomeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton3ActionPerformed(evt);
            }
        });
        jPanel19.add(HomeButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));
        jPanel19.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 12));
        jPanel19.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 30, 12));

        MapButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/brazil-map.png"))); // NOI18N
        MapButton3.setBorderPainted(false);
        MapButton3.setContentAreaFilled(false);
        MapButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButton3ActionPerformed(evt);
            }
        });
        jPanel19.add(MapButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 40));

        jPanel20.setBackground(new java.awt.Color(33, 63, 118));
        jPanel20.setBorder(null);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        ParaButton3.setForeground(new java.awt.Color(254, 254, 254));
        ParaButton3.setText("Pará");
        ParaButton3.setBorder(null);
        ParaButton3.setBorderPainted(false);
        ParaButton3.setContentAreaFilled(false);
        ParaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(ParaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 100, 100));

        RondoniaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        RondoniaButton3.setForeground(new java.awt.Color(254, 254, 254));
        RondoniaButton3.setText("Rondônia");
        RondoniaButton3.setBorder(null);
        RondoniaButton3.setBorderPainted(false);
        RondoniaButton3.setContentAreaFilled(false);
        RondoniaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RondoniaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(RondoniaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 100, 50));

        RoraimaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        RoraimaButton3.setForeground(new java.awt.Color(254, 254, 254));
        RoraimaButton3.setText("Roraima");
        RoraimaButton3.setBorder(null);
        RoraimaButton3.setBorderPainted(false);
        RoraimaButton3.setContentAreaFilled(false);
        RoraimaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoraimaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(RoraimaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, 80));

        TocantinsButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        TocantinsButton3.setForeground(new java.awt.Color(254, 254, 254));
        TocantinsButton3.setText("Tocantins");
        TocantinsButton3.setBorder(null);
        TocantinsButton3.setBorderPainted(false);
        TocantinsButton3.setContentAreaFilled(false);
        TocantinsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TocantinsButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(TocantinsButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 100, 40));

        MatoGrossoDoSulBUtton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MatoGrossoDoSulBUtton3.setForeground(new java.awt.Color(254, 254, 254));
        MatoGrossoDoSulBUtton3.setText("Mato Grosso do Sul");
        MatoGrossoDoSulBUtton3.setBorder(null);
        MatoGrossoDoSulBUtton3.setBorderPainted(false);
        MatoGrossoDoSulBUtton3.setContentAreaFilled(false);
        MatoGrossoDoSulBUtton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatoGrossoDoSulBUtton3ActionPerformed(evt);
            }
        });
        jPanel20.add(MatoGrossoDoSulBUtton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 190, 50));

        RioGrandeDoSulBUtton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        RioGrandeDoSulBUtton3.setForeground(new java.awt.Color(254, 254, 254));
        RioGrandeDoSulBUtton3.setText("Rio Grande do Sul");
        RioGrandeDoSulBUtton3.setBorder(null);
        RioGrandeDoSulBUtton3.setBorderPainted(false);
        RioGrandeDoSulBUtton3.setContentAreaFilled(false);
        RioGrandeDoSulBUtton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RioGrandeDoSulBUtton3ActionPerformed(evt);
            }
        });
        jPanel20.add(RioGrandeDoSulBUtton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 190, 60));

        AcreButton8.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        AcreButton8.setForeground(new java.awt.Color(254, 254, 254));
        AcreButton8.setText("Acre");
        AcreButton8.setBorder(null);
        AcreButton8.setBorderPainted(false);
        AcreButton8.setContentAreaFilled(false);
        AcreButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcreButton8ActionPerformed(evt);
            }
        });
        jPanel20.add(AcreButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 70, 40));

        AmazonasButton4.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        AmazonasButton4.setForeground(new java.awt.Color(254, 254, 254));
        AmazonasButton4.setText("Amazonas");
        AmazonasButton4.setBorder(null);
        AmazonasButton4.setBorderPainted(false);
        AmazonasButton4.setContentAreaFilled(false);
        AmazonasButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmazonasButton4ActionPerformed(evt);
            }
        });
        jPanel20.add(AmazonasButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 190, 110));

        AmapaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        AmapaButton3.setForeground(new java.awt.Color(254, 254, 254));
        AmapaButton3.setText("Amapá");
        AmapaButton3.setBorder(null);
        AmapaButton3.setBorderPainted(false);
        AmapaButton3.setContentAreaFilled(false);
        AmapaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmapaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(AmapaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 90, 80));

        MaranhaoButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MaranhaoButton3.setForeground(new java.awt.Color(254, 254, 254));
        MaranhaoButton3.setText("Maranhão");
        MaranhaoButton3.setBorder(null);
        MaranhaoButton3.setBorderPainted(false);
        MaranhaoButton3.setContentAreaFilled(false);
        MaranhaoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaranhaoButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(MaranhaoButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 110, 70));

        PiauiButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        PiauiButton3.setForeground(new java.awt.Color(254, 254, 254));
        PiauiButton3.setText("Piauí");
        PiauiButton3.setBorder(null);
        PiauiButton3.setBorderPainted(false);
        PiauiButton3.setContentAreaFilled(false);
        PiauiButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiauiButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(PiauiButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 60, 60));

        BahiaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        BahiaButton3.setForeground(new java.awt.Color(254, 254, 254));
        BahiaButton3.setText("Bahia");
        BahiaButton3.setBorder(null);
        BahiaButton3.setBorderPainted(false);
        BahiaButton3.setContentAreaFilled(false);
        BahiaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahiaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(BahiaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 90, 70));

        SantacatButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        SantacatButton3.setForeground(new java.awt.Color(254, 254, 254));
        SantacatButton3.setText("Santa Catarina");
        SantacatButton3.setBorder(null);
        SantacatButton3.setBorderPainted(false);
        SantacatButton3.setContentAreaFilled(false);
        SantacatButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SantacatButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(SantacatButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 160, 40));

        ParanaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        ParanaButton3.setForeground(new java.awt.Color(254, 254, 254));
        ParanaButton3.setText("Paraná");
        ParanaButton3.setBorder(null);
        ParanaButton3.setBorderPainted(false);
        ParanaButton3.setContentAreaFilled(false);
        ParanaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParanaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(ParanaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 80, 40));

        SaoPauloButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        SaoPauloButton3.setForeground(new java.awt.Color(254, 254, 254));
        SaoPauloButton3.setText("São Paulo");
        SaoPauloButton3.setBorder(null);
        SaoPauloButton3.setBorderPainted(false);
        SaoPauloButton3.setContentAreaFilled(false);
        SaoPauloButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaoPauloButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(SaoPauloButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 110, 50));

        GoiasButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        GoiasButton3.setForeground(new java.awt.Color(254, 254, 254));
        GoiasButton3.setText("Goiás");
        GoiasButton3.setBorder(null);
        GoiasButton3.setBorderPainted(false);
        GoiasButton3.setContentAreaFilled(false);
        GoiasButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoiasButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(GoiasButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 70, 50));

        MinasGeraisButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MinasGeraisButton3.setForeground(new java.awt.Color(254, 254, 254));
        MinasGeraisButton3.setText("Minas Gerais");
        MinasGeraisButton3.setBorder(null);
        MinasGeraisButton3.setBorderPainted(false);
        MinasGeraisButton3.setContentAreaFilled(false);
        MinasGeraisButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinasGeraisButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(MinasGeraisButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, -1, 60));

        RioDEJaneiroButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        RioDEJaneiroButton3.setForeground(new java.awt.Color(254, 254, 254));
        RioDEJaneiroButton3.setText("Rio de Janeiro");
        RioDEJaneiroButton3.setBorder(null);
        RioDEJaneiroButton3.setBorderPainted(false);
        RioDEJaneiroButton3.setContentAreaFilled(false);
        RioDEJaneiroButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RioDEJaneiroButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(RioDEJaneiroButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 140, 30));

        ESButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        ESButton3.setForeground(new java.awt.Color(254, 254, 254));
        ESButton3.setText("Espírito Santo");
        ESButton3.setBorder(null);
        ESButton3.setBorderPainted(false);
        ESButton3.setContentAreaFilled(false);
        ESButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(ESButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 140, 50));

        SergipeButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        SergipeButton3.setForeground(new java.awt.Color(254, 254, 254));
        SergipeButton3.setText("Sergipe");
        SergipeButton3.setBorder(null);
        SergipeButton3.setBorderPainted(false);
        SergipeButton3.setContentAreaFilled(false);
        SergipeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SergipeButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(SergipeButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 120, 20));

        ParaibaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        ParaibaButton3.setForeground(new java.awt.Color(254, 254, 254));
        ParaibaButton3.setText("Paraíba");
        ParaibaButton3.setBorder(null);
        ParaibaButton3.setBorderPainted(false);
        ParaibaButton3.setContentAreaFilled(false);
        ParaibaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaibaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(ParaibaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 140, 20));

        PernambucoButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        PernambucoButton3.setForeground(new java.awt.Color(254, 254, 254));
        PernambucoButton3.setText("Pernambuco");
        PernambucoButton3.setBorder(null);
        PernambucoButton3.setBorderPainted(false);
        PernambucoButton3.setContentAreaFilled(false);
        PernambucoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PernambucoButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(PernambucoButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 150, 30));

        RGDNButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        RGDNButton3.setForeground(new java.awt.Color(254, 254, 254));
        RGDNButton3.setText("Rio Grande do Norte");
        RGDNButton3.setBorder(null);
        RGDNButton3.setBorderPainted(false);
        RGDNButton3.setContentAreaFilled(false);
        RGDNButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGDNButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(RGDNButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 200, 20));

        MatoGrossoButton19.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        MatoGrossoButton19.setForeground(new java.awt.Color(254, 254, 254));
        MatoGrossoButton19.setText("Mato Grosso");
        MatoGrossoButton19.setBorder(null);
        MatoGrossoButton19.setBorderPainted(false);
        MatoGrossoButton19.setContentAreaFilled(false);
        MatoGrossoButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatoGrossoButton19ActionPerformed(evt);
            }
        });
        jPanel20.add(MatoGrossoButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 130, 80));

        CearaButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        CearaButton3.setForeground(new java.awt.Color(254, 254, 254));
        CearaButton3.setText("Ceará");
        CearaButton3.setBorder(null);
        CearaButton3.setBorderPainted(false);
        CearaButton3.setContentAreaFilled(false);
        CearaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CearaButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(CearaButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 70, 40));

        AlagoasButton3.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        AlagoasButton3.setForeground(new java.awt.Color(254, 254, 254));
        AlagoasButton3.setText("Alagoas");
        AlagoasButton3.setBorder(null);
        AlagoasButton3.setBorderPainted(false);
        AlagoasButton3.setContentAreaFilled(false);
        AlagoasButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlagoasButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(AlagoasButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 140, 20));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/mapa-do-brasil-hcv-hi.png"))); // NOI18N
        jPanel20.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jPanel21.setBackground(new java.awt.Color(52, 79, 127));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("URW Gothic L", 0, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(254, 254, 254));
        jLabel35.setText("Mapa do Brasil");
        jPanel21.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Regiões3.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        Regiões3.setForeground(new java.awt.Color(1, 1, 1));
        Regiões3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/002-brazil-1.png"))); // NOI18N
        Regiões3.setText("Mapa com regiões");
        Regiões3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Regiões3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regiões3ActionPerformed(evt);
            }
        });
        jPanel21.add(Regiões3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 190, 40));

        Geral3.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        Geral3.setForeground(new java.awt.Color(1, 1, 1));
        Geral3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/001-brazil.png"))); // NOI18N
        Geral3.setText("Mapa com Estados");
        Geral3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Geral3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Geral3ActionPerformed(evt);
            }
        });
        jPanel21.add(Geral3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 190, -1));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 120));

        jLabel36.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(254, 254, 254));
        jLabel36.setText("Clique no nome de um estado para ver suas informações ");
        jPanel20.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel22.setBackground(new java.awt.Color(52, 79, 127));

        jLabel37.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(254, 254, 254));
        jLabel37.setText("Unidade Federativa:");

        jLabel38.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(254, 254, 254));
        jLabel38.setText("Capital:");

        jLabel39.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(254, 254, 254));
        jLabel39.setText("Área(km²):");

        jLabel40.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(254, 254, 254));
        jLabel40.setText("É um estado litoraneo: ");

        jLabel41.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(254, 254, 254));
        jLabel41.setText("Região");

        jLabel42.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(254, 254, 254));
        jLabel42.setText("Número de habitantes:");

        jLabel43.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(254, 254, 254));
        jLabel43.setText("Fronteira com o(s) país(es): ");

        jPanel23.setBackground(new java.awt.Color(144, 169, 213));
        jPanel23.setBorder(null);
        jPanel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator38.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator38.setForeground(new java.awt.Color(1, 1, 1));
        jSeparator38.setBorder(null);

        FUlabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        CapitalLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        RegionLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        PopulationLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        AreaLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        CoastalLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        FrontierLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        CuriosityLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoastalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopulationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapitalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrontierLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CuriosityLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(FUlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator38, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator39, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator42, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator41, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addComponent(jSeparator43, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(FUlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CapitalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PopulationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AreaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CoastalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FrontierLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CuriosityLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jSeparator38, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jSeparator39, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jSeparator40, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jSeparator41, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jSeparator42, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jSeparator43, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        jLabel44.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(254, 254, 254));
        jLabel44.setText("Curiosidade");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel37))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel40))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel39))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel38))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel41)
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel39)
                .addGap(8, 8, 8)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addGap(8, 8, 8)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addGap(40, 40, 40))
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 390, 350));

        jPanel24.setBackground(new java.awt.Color(68, 107, 176));
        jPanel24.setForeground(new java.awt.Color(96, 165, 219));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(254, 254, 254));
        jLabel45.setText("Você escolheu o nomedoestado !");
        jLabel45.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabel45ComponentResized(evt);
            }
        });
        jPanel24.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 231, -1, 28));

        jLabel46.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(254, 254, 254));
        jLabel46.setText("Você escolheu o nomedoestado !");
        jPanel24.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 231, -1, 28));

        NomeEstado.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        NomeEstado.setForeground(new java.awt.Color(254, 254, 254));
        NomeEstado.setText("Nada selecionado");
        jPanel24.add(NomeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 28));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 50));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1170, 640));

        QuizButton1.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        QuizButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/test-quiz.png"))); // NOI18N
        QuizButton1.setBorderPainted(false);
        QuizButton1.setContentAreaFilled(false);
        QuizButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButton1ActionPerformed(evt);
            }
        });
        jPanel19.add(QuizButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 60, 56));
        jPanel19.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 30, 12));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geocatch/draw/switch (1).png"))); // NOI18N
        CloseButton.setBorderPainted(false);
        CloseButton.setContentAreaFilled(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel19.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 50, 50));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton3ActionPerformed
        // TODO add your handling code here:

        new MyMain().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_HomeButton3ActionPerformed

    private void MapButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButton3ActionPerformed
        // TODO add your handling code here:
        new MapView().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_MapButton3ActionPerformed

    private void ParaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaButton3ActionPerformed

    }//GEN-LAST:event_ParaButton3ActionPerformed

    private void RondoniaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RondoniaButton3ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_RondoniaButton3ActionPerformed

    private void RoraimaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoraimaButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoraimaButton3ActionPerformed

    private void TocantinsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TocantinsButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TocantinsButton3ActionPerformed

    private void MatoGrossoDoSulBUtton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatoGrossoDoSulBUtton3ActionPerformed

    }//GEN-LAST:event_MatoGrossoDoSulBUtton3ActionPerformed

    private void RioGrandeDoSulBUtton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RioGrandeDoSulBUtton3ActionPerformed

    }//GEN-LAST:event_RioGrandeDoSulBUtton3ActionPerformed

    private void AcreButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcreButton8ActionPerformed

    }//GEN-LAST:event_AcreButton8ActionPerformed

    private void AmazonasButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmazonasButton4ActionPerformed

    }//GEN-LAST:event_AmazonasButton4ActionPerformed

    private void AmapaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmapaButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_AmapaButton3ActionPerformed

    private void MaranhaoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaranhaoButton3ActionPerformed

    }//GEN-LAST:event_MaranhaoButton3ActionPerformed

    private void PiauiButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiauiButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PiauiButton3ActionPerformed

    private void BahiaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahiaButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BahiaButton3ActionPerformed

    private void SantacatButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SantacatButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SantacatButton3ActionPerformed

    private void ParanaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParanaButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ParanaButton3ActionPerformed

    private void SaoPauloButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaoPauloButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaoPauloButton3ActionPerformed

    private void GoiasButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoiasButton3ActionPerformed

    }//GEN-LAST:event_GoiasButton3ActionPerformed

    private void MinasGeraisButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinasGeraisButton3ActionPerformed

    }//GEN-LAST:event_MinasGeraisButton3ActionPerformed

    private void RioDEJaneiroButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RioDEJaneiroButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RioDEJaneiroButton3ActionPerformed

    private void ESButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESButton3ActionPerformed

    }//GEN-LAST:event_ESButton3ActionPerformed

    private void SergipeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SergipeButton3ActionPerformed

    }//GEN-LAST:event_SergipeButton3ActionPerformed

    private void ParaibaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaibaButton3ActionPerformed

    }//GEN-LAST:event_ParaibaButton3ActionPerformed

    private void PernambucoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PernambucoButton3ActionPerformed

    }//GEN-LAST:event_PernambucoButton3ActionPerformed

    private void RGDNButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGDNButton3ActionPerformed

    }//GEN-LAST:event_RGDNButton3ActionPerformed

    private void MatoGrossoButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatoGrossoButton19ActionPerformed

    }//GEN-LAST:event_MatoGrossoButton19ActionPerformed

    private void CearaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CearaButton3ActionPerformed

    }//GEN-LAST:event_CearaButton3ActionPerformed

    private void AlagoasButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlagoasButton3ActionPerformed

    }//GEN-LAST:event_AlagoasButton3ActionPerformed

    private void Regiões3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regiões3ActionPerformed

    }//GEN-LAST:event_Regiões3ActionPerformed

    private void Geral3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Geral3ActionPerformed

    }//GEN-LAST:event_Geral3ActionPerformed

    private void jLabel45ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel45ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45ComponentResized

    private void MapButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButton4ActionPerformed
        // TODO add your handling code here:
          new MapView().setVisible(true);//que quer abrir
        dispose();
        
        
    }//GEN-LAST:event_MapButton4ActionPerformed

    private void HomeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton4ActionPerformed
        // TODO add your handling code here:
         new MyMain().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_HomeButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         new QuickQuiz().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QuizButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButton1ActionPerformed
        // TODO add your handling code here:
        new QuizExplain().setVisible(true);//que quer abrir
        
        dispose();
    }//GEN-LAST:event_QuizButton1ActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);

    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizExplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizExplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizExplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizExplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new QuizExplain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcreButton8;
    private javax.swing.JButton AlagoasButton3;
    private javax.swing.JButton AmapaButton3;
    private javax.swing.JButton AmazonasButton4;
    private javax.swing.JLabel AreaLabel3;
    private javax.swing.JButton BahiaButton3;
    private javax.swing.JLabel CapitalLabel3;
    private javax.swing.JButton CearaButton3;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel CoastalLabel3;
    private javax.swing.JLabel CuriosityLabel3;
    private javax.swing.JButton ESButton3;
    private javax.swing.JLabel FUlabel3;
    private javax.swing.JLabel FrontierLabel3;
    private javax.swing.JButton Geral3;
    private javax.swing.JButton GoiasButton3;
    private javax.swing.JButton HomeButton3;
    private javax.swing.JButton HomeButton4;
    private javax.swing.JButton MapButton3;
    private javax.swing.JButton MapButton4;
    private javax.swing.JButton MaranhaoButton3;
    private javax.swing.JButton MatoGrossoButton19;
    private javax.swing.JButton MatoGrossoDoSulBUtton3;
    private javax.swing.JButton MinasGeraisButton3;
    private javax.swing.JLabel NomeEstado;
    private javax.swing.JButton ParaButton3;
    private javax.swing.JButton ParaibaButton3;
    private javax.swing.JButton ParanaButton3;
    private javax.swing.JButton PernambucoButton3;
    private javax.swing.JButton PiauiButton3;
    private javax.swing.JLabel PopulationLabel3;
    private javax.swing.JButton QuizButton1;
    private javax.swing.JButton RGDNButton3;
    private javax.swing.JLabel RegionLabel3;
    private javax.swing.JButton Regiões3;
    private javax.swing.JButton RioDEJaneiroButton3;
    private javax.swing.JButton RioGrandeDoSulBUtton3;
    private javax.swing.JButton RondoniaButton3;
    private javax.swing.JButton RoraimaButton3;
    private javax.swing.JButton SantacatButton3;
    private javax.swing.JButton SaoPauloButton3;
    private javax.swing.JButton SergipeButton3;
    private javax.swing.JButton TocantinsButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
